name: dnskills
version: 0.1.0
author: kalhartt
description: A sample application
homepage: https://github.com/kalhartt/dnskills
documentation: https://github.com/kalhartt/dnskills
environment:
  sdk: '>=0.7.1'
dependencies:
  polymer: '>=0.7.1'
